# https://neptune.ai

neptune:
  _target_: lightning.pytorch.loggers.neptune.NeptuneLogger
  api_key: "eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vYXBwLm5lcHR1bmUuYWkiLCJhcGlfdXJsIjoiaHR0cHM6Ly9hcHAubmVwdHVuZS5haSIsImFwaV9rZXkiOiI0ZTdkZWNlYS1jMGQwLTRkZTctYmUxMS1hZjRlZDY5NGU0OTUifQ=="
  project: mine-ai/DCLC3
  log_model_checkpoints: False
  prefix: ""
